# Base image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package files first to install dependencies
COPY JSNetwork/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY JSNetwork .

# Expose the port your app runs on
EXPOSE 8080

# Start the server
CMD ["node", "app.js"]
