# Base image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy dependency files
COPY gmailish-web/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY gmailish-web ./

# Expose React dev server port
EXPOSE 3000

# Start React development server
CMD ["npm", "start"]
