
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_react
    ports:
      - "3000:3000"
    depends_on:
      - express
    networks:
      - server-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
    - server-network

  express:
    build:
      context: .
      dockerfile: ./Dockerfile_express
    ports:
      - "8080:8080"
    container_name: express
    depends_on:
      - cppserver
      - mongo
    networks:
      - server-network
    environment:
      - PORT=8080

  cppserver:
    build:
      context: .
      dockerfile: ./Dockerfile_server
    ports:
      - "5555:5555"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
