
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile_react
    ports:
      - "3000:3000"
    depends_on:
      - express
    networks:
      - server-network

  express:
    build:
      context: .
      dockerfile: ./Dockerfile_express
    ports:
      - "8080:8080"
    depends_on:
      - cppserver
    networks:
      - server-network
    environment:
      - NODE_ENV=development
      - PORT=8080

  cppserver:
    build:
      context: .
      dockerfile: ./Dockerfile_server
    ports:
      - "5555:5555"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
